# Site settings
title: "Ryan T. Hamilton's Homepage"
email: ryan@astroinclined.com
description: "Yes, I really chose a Commodore 64 theme for my website."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrobokonon.github.io" # the base hostname & protocol for your site
twitter_username: astrobokonon
github_username:  astrobokonon

# Build settings
markdown: kramdown
