# Site settings
title: "Ryan T. Hamilton's Homepage"
description: "Head of Instrumentation at Lowell Observatory, and former Instrument Scientist for HAWC+ and FLITECAM on NASA's SOFIA. I don't think I'll ever get over Macho Grande."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrobokonon.github.io" # the base hostname & protocol for your site
#twitter_username: astrobokonon
github_profile: https://github.com/astrobokonon/
linkedin: http://linkedin.com/astroryan
aboutme: https://about.me/ryan.hamilton/

#weblinkurl_1:
#weblinktxt_1:

# Build settings
markdown: kramdown
