# Site settings
title: "Ryan T. Hamilton's Homepage"
description: "Head of Instrumentation at Lowell Observatory, and former Instrument Scientist for HAWC+ and FLITECAM on NASA's SOFIA. I don't think I'll ever get over Macho Grande."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrobokonon.github.io" # the base hostname & protocol for your site
#email_whex: "ryan0x40astroinclined0x2Ecom"
emailName: "ryan"
emailDomain: "astroinclined.com"
#twitter: https://twitter.com/astrobokonon
github_profile: https://github.com/astrobokonon/
linkedin: http://linkedin.com/in/astroryan
aboutme: https://about.me/ryan.hamilton/
adslib: https://ui.adsabs.harvard.edu/public-libraries/Oi043_WSSa2RvR0mXP3l6g

#weblinkurl_1:
#weblinktxt_1:

# Build settings
markdown: kramdown
