# Site settings
title: A C64 Theme for Jekyll
email: regmtait@gmail.com
description: "Get blogging like it's 1985 with this Commodore 64 theme for Jekyll, the simple, blog aware, static site generator from GitHub."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrobokonon.github.io" # the base hostname & protocol for your site
twitter_username: astrobokonon
github_username:  astrobokonon

# Build settings
markdown: kramdown
