# Site settings
title: "Ryan T. Hamilton's Homepage"
weblinkurl_1: http://opensciencecafe.org/
weblinktxt_1: OpenScienceCafe
weblinkurl_2: https://about.me/ryan.hamilton/
weblinktxt_2: About.me Metapage
description: "Instrument Scientist for HAWC+ on NASA's Stratospheric Observatory for Infrared Astronomy (SOFIA). I don't think I'll ever get over Macho Grande."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrobokonon.github.io" # the base hostname & protocol for your site
twitter_username: astrobokonon
github_username:  astrobokonon

# Build settings
markdown: kramdown
